name: CI
on:
  pull_request:
  push:
    branches: ["main"]
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: TopoToolbox/actions/checkout@main
      - name: Build SWT
        run: CFLAGS="-Werror -Wall -Wextra -Wpedantic -Wno-unused-parameter" make
      - name: Run tests
        run: make -k check
